--1. What are the details of all cars purchased in the year 2022?
SELECT
	c.car_id, 
	c.make, 
	c."type" , 
	c."style" , 
	c."cost_$",
	s.purchase_date
FROM 
	challenge_1.cars c
LEFT JOIN 
	challenge_1.sales s 
		ON c.car_id = s.car_id 
WHERE 
	--s.purchase_date::varchar LIKE '2022-%'
	DATE_PART('year', s.purchase_date) = 2022 
ORDER BY 
	s.purchase_date ;

-----or -------------------- this will be fast
SELECT
    c.car_id, 
    c.make, 
    c."type", 
    c."style", 
    c."cost_$",
    s.purchase_date
FROM
    challenge_1.cars c
JOIN 
	challenge_1.sales s
		ON c.car_id = s.car_id
WHERE
    s.purchase_date >= '2022-01-01' AND s.purchase_date < '2023-01-01'
ORDER BY 
	s.purchase_date;


--2. What is the total number of cars sold by each salesperson?
SELECT
    sp.salesman_id, 
    sp.name, 
    sp.age, 
    sp.city,
    COUNT(*) AS total_car_sold
FROM
    challenge_1.salespersons sp
JOIN 
	challenge_1.sales s 
		ON s.salesman_id = sp.salesman_id
GROUP BY
	sp.salesman_id;

--3. What is the total revenue generated by each salesperson?
SELECT
	sp.salesman_id, 
	sp.name, sp.age, 
	sp.city,
	sum(c."cost_$") AS total_revenue_generated
FROM 
	challenge_1.salespersons sp 
JOIN 
	challenge_1.sales s
		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c 
		ON s.car_id = c.car_id 
GROUP BY 
	sp.salesman_id ;


--4. What are the details of the cars sold by each salesperson?
SELECT
    sp.salesman_id,
    sp.name AS sales_person_name,
    c.car_id,
    c.make,
    c."type",
    c."style",
    c."cost_$",
    s.purchase_date
FROM
    challenge_1.salespersons sp
JOIN 
	challenge_1.sales s
    		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c
    		ON s.car_id = c.car_id;


--5. What is the total revenue generated by each car type?
SELECT
	c."type", 
	sum(c."cost_$")
FROM 
	challenge_1.salespersons sp 
JOIN 
	challenge_1.sales s
		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c 
		ON s.car_id = c.car_id 
GROUP BY 
	c."type";

--6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
SELECT
    c.car_id,
    c.make,
    c."type",
    c."style",
    c."cost_$",
    s.purchase_date
FROM
    challenge_1.salespersons sp
JOIN 
	challenge_1.sales s
    		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c
    		ON s.car_id = c.car_id
WHERE
    DATE_PART('year', s.purchase_date) = 2021 AND sp."name" = 'Emily Wong'
ORDER BY 
	s.purchase_date;


--7. What is the total revenue generated by the sales of 'Hatchback' cars?
SELECT
	c."style" , 
	sum(c."cost_$") AS total_revenue_by_car_Hatchback
FROM 
	challenge_1.salespersons sp 
JOIN 
	challenge_1.sales s
		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c 
		ON s.car_id = c.car_id
WHERE 
	c."style" = 'Hatchback'
GROUP BY 
	c."style";

-------------- or------------------
SELECT
    'Hatchback' AS style,
    SUM(c."cost_$") AS total_revenue_by_car_Hatchback
FROM
    challenge_1.salespersons sp
JOIN 
	challenge_1.sales s
   		 ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c
    		ON s.car_id = c.car_id
WHERE
    c."style" = 'Hatchback';


--8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT
	c."style" , 
	sum(c."cost_$") AS total_revenue_by_car_SUV_2022
FROM 
	challenge_1.salespersons sp 
JOIN 
	challenge_1.sales s
		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c 
		ON s.car_id = c.car_id
WHERE 
	c."style" = 'SUV' AND DATE_PART('year', s.purchase_date) = 2022
GROUP BY 
	c."style";

-----or -----------

SELECT
    'SUV' AS style,
    SUM(c."cost_$") AS total_revenue_by_car_SUV_2022
FROM
    challenge_1.salespersons sp
LEFT JOIN 
	challenge_1.sales s
   		ON s.salesman_id = sp.salesman_id
LEFT JOIN 
	challenge_1.cars c
    		ON s.car_id = c.car_id
WHERE
    c."style" = 'SUV' AND DATE_PART('year', s.purchase_date) = 2022;


--9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT
    sp."name" AS sales_person_name, sp.city,
    COUNT(*) AS total_number_of_car_sold
FROM
    challenge_1.salespersons sp
JOIN 
	challenge_1.sales s 
		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c 
		ON s.car_id = c.car_id
WHERE
    DATE_PART('year', s.purchase_date) = 2023
GROUP BY 
	sp."name",
	sp.city
ORDER BY 
	total_number_of_car_sold DESC
LIMIT 1;

--10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
SELECT
    sp."name" AS sales_person_name, sp.age,
    SUM(c."cost_$") AS total_revenue_generated
FROM
    challenge_1.salespersons sp
JOIN 
	challenge_1.sales s 
		ON s.salesman_id = sp.salesman_id
JOIN 
	challenge_1.cars c 
		ON s.car_id = c.car_id
WHERE
    DATE_PART('year', s.purchase_date) = 2022
GROUP BY 
	sp."name", 
	sp.age
ORDER BY 
	total_revenue_generated DESC
LIMIT 1;
